 funcion **range** genera una secuencia de enteros espaciados por igual. produce enteros hasta el valor final pero sin incluirlo; se puede utilizar para aplicar instrucciones a distintas secuencias segun

In [ ]:
lista = list(range(20))
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [ ]:
lista1 = list(range(0,100,7)) #lista que comienza en cero hasta 100 con incrementos de 7 unidades
lista1

[0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]

In [ ]:
list(range(40,0,-5))

[40, 35, 30, 25, 20, 15, 10, 5]

**array** es una estructura que sirve para almacenar varios valores relacionados dentro de unsa sola variable. Un array es una coleccion ordenada de datos.


In [ ]:
list1 = (1, 75, 455) #creamos listas simples
list2 = (2, 50, 409)

print(list1 + list2) #concadenamos las listas, se imprimen en orden

(1, 75, 455, 2, 50, 409)


importamos la biblioteca numpy

In [ ]:
import numpy as np #calculos matematicos eficientes

La funcion np.array() convierte una lista en un objeto ndarray

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b) #nos imprime como si fueran vectores

[5 7 9]


In [ ]:
A = np.array([[1,2],[3,4]])

B = np.array([[2,0],[1,2]])
print(A@B) #producto matricial¿?

[[ 4  4]
 [10  8]]


Dos listas de arrays

In [ ]:
datos = [[1,2,3,4], [5.3,62.3,7,8]]
arr = np.array(datos)
print (arr)

[[ 1.   2.   3.   4. ]
 [ 5.3 62.3  7.   8. ]]


otra funcion que nos permite crear un array NumPy es **numpy.range**. Esta funcion genera un conjunto de numeros entre un vaor de inicio y uno final, pudiendo especificar un incremento entre los valores

In [ ]:
arr1 = np.arange(1,10,.05) #primero es de un inicio, un final, el incremento que tendra
print(arr1)

[1.   1.05 1.1  1.15 1.2  1.25 1.3  1.35 1.4  1.45 1.5  1.55 1.6  1.65
 1.7  1.75 1.8  1.85 1.9  1.95 2.   2.05 2.1  2.15 2.2  2.25 2.3  2.35
 2.4  2.45 2.5  2.55 2.6  2.65 2.7  2.75 2.8  2.85 2.9  2.95 3.   3.05
 3.1  3.15 3.2  3.25 3.3  3.35 3.4  3.45 3.5  3.55 3.6  3.65 3.7  3.75
 3.8  3.85 3.9  3.95 4.   4.05 4.1  4.15 4.2  4.25 4.3  4.35 4.4  4.45
 4.5  4.55 4.6  4.65 4.7  4.75 4.8  4.85 4.9  4.95 5.   5.05 5.1  5.15
 5.2  5.25 5.3  5.35 5.4  5.45 5.5  5.55 5.6  5.65 5.7  5.75 5.8  5.85
 5.9  5.95 6.   6.05 6.1  6.15 6.2  6.25 6.3  6.35 6.4  6.45 6.5  6.55
 6.6  6.65 6.7  6.75 6.8  6.85 6.9  6.95 7.   7.05 7.1  7.15 7.2  7.25
 7.3  7.35 7.4  7.45 7.5  7.55 7.6  7.65 7.7  7.75 7.8  7.85 7.9  7.95
 8.   8.05 8.1  8.15 8.2  8.25 8.3  8.35 8.4  8.45 8.5  8.55 8.6  8.65
 8.7  8.75 8.8  8.85 8.9  8.95 9.   9.05 9.1  9.15 9.2  9.25 9.3  9.35
 9.4  9.45 9.5  9.55 9.6  9.65 9.7  9.75 9.8  9.85 9.9  9.95]


In [ ]:
arrejemplo = np.arange (0, 15, 3) #aqui quiero que empiece en 0, acabe en 15 y vaya de 3 en 3
print(arrejemplo)


[ 0  3  6  9 12]


En NumPy, es posible convertir un array de un tipo de dato a otro de forma explicita usando el metodo astype() del ndarray.

In [ ]:
arr2 = np.array ([1,2,3,4,5])
print(arr2.dtype)

int64


In [ ]:
arr3 = np.array (['pepe', 'pecas', 'pica', 'papas'])
print(arr3.dtype)

<U5


In [ ]:
float_arr = arr2.astype(float)
print(float_arr)

[1. 2. 3. 4. 5.]


In [ ]:
#De flotantes a enteros
array4 = np.array([4.5, 7.85, 6.369, 9.57])
print(array4.dtype)

float64


In [ ]:
int_array4 = array4.astype(int) #usamos ahora int para pasar de float a int
print(int_array4)

[4 7 6 9]


In [ ]:
#de numeros a letras
C = np.array([100, 200 ,300])
D = C.astype(str) #usamos str por string para que sea cadena

print(D)

['100' '200' '300']


**EJEMPLO**
* con las matrices de A y B
* Calcular el producto matricial
* calcular la traspuesta de A y B
* verificar si A es simetrica
* Calcular la inversa de B (si existe) y comprueba si es su inversa

In [ ]:
matrizA = np.array(([2,4,6], [4,5,7], [6,7,9])) #para que se vean como matrices usamos el np.array

matrizB = np.array(([1,2,3], [0,1,4], [5,6,0]))

print(matrizA)

print(matrizB)

[[2 4 6]
 [4 5 7]
 [6 7 9]]
[[1 2 3]
 [0 1 4]
 [5 6 0]]


In [ ]:
print(matrizA@matrizB) #producto matricial, tambien podemos usar np.dot(matrizA,matrizB)

[[32 44 22]
 [39 55 32]
 [51 73 46]]


In [ ]:
matrizA_T = matrizA.T #Para la transpuesta
matrizB_T = matrizB.T

print('\nTranspuerta de A:')
print(matrizA_T)

print('\nTranspuesta de B:')
print(matrizB_T)


Transpuerta de A:
[[2 4 6]
 [4 5 7]
 [6 7 9]]

Transpuesta de B:
[[1 0 5]
 [2 1 6]
 [3 4 0]]


In [ ]:
simetria = np.array_equal(A, matrizA.T) #para saber si es simetría

un **diccionario** es una estructura de datos que permite guardar informacion en pares: clave -->valor.
* a diferencia de las listas (que usan posiciones), los diccionares usan nombres (**claves**) para acceder a los datos
* se usan llaves {}

In [ ]:
reactor = {
    'tipo': 'CSTR',
    'volumen': 5.0,
    'temperatura': 350,
    'presion': 2.5,
}
reactor

{'tipo': 'CSTR', 'volumen': 5.0, 'temperatura': 350, 'presion': 2.5}

In [ ]:
#ejemplo de diccionario
cafe = {
    'leche': 'deslactosada light',
    'tamaño' : ' chico',
    'tipo' : 'descafeinado',
    'nombre': 'yael'
}
print(cafe)

{'leche': 'deslactosada light', 'tamaño': ' chico', 'tipo': 'descafeinado', 'nombre': 'yael'}


Se puede acceder a los elementos, insertarlos o formar conjuntos con ellos utilizando la misma sintaxis para acceder a los elementos de una lista.

In [ ]:
print(cafe['tamaño'])

 chico


In [ ]:
cafe['tamaño'] = 'grande' #cambiar un elemento en este caso el de tamaño
cafe['azúcar'] = 'mascabado' #para agregar un nuevo elemento

In [ ]:
print(cafe)

{'leche': 'deslactosada light', 'tamaño': 'grande', 'tipo': 'descafeinado', 'nombre': 'yael', 'azucar': 'mascabado', 'azúcar': 'mascabado'}


Para que usar diccionarios?
para datos que queramos generar


**Funciones en python**
Las funciones son el metodo mas importante en python para organizr, reutilizar y simplificar el codigo

Regla general:

Si un mismo código se va a usar mas de una vez, conviene escribir una funcion.

En python se declaran con la palabra clave **def**, contiene un bloque de codigo, con uso opcional de la palabra clave **return**

In [ ]:
def sumar (a, b): #lo que se encuentra dentro de los parentesis son los parametros de entrada
  x = a + b
  return x

¿Como usar la funcion?

In [ ]:
sumar(15,75)

90

In [ ]:
def prom (a,b,c,d):
  prom = (a+b+c+d)/4
  return prom

In [ ]:
prom(45,12,546,89)

173.0